### ISSUE TITLE
The status of this repo

### ISSUE THREAD

**Issue by pinepain** [TheJumpCloud/jumpcloud-ruby-gem#13]
Hi! Thanks for the decent service.

I'd like to clarify what it the current state of this repo and whether it is still supported. I see that it still operates on Tags which are currently phasing out. Also the repo has opened PRs and issues from 2015, which looks a bit odd.

Could you provide us with further plans on this repo and what alternatives you would recommend to use?

**Comment by run-o** [comment]
@pinepain 
Hi there!
This repository is now deprecated. We have a new repository for the Ruby API client which supports both tags and groups (API v1 and v2):
https://github.com/TheJumpCloud/jcapi-ruby
Let me know if you run into any issues with that new repo.

Renaud.

**Comment by pinepain** [comment]
Thanks for quick repl!. That client is decent, thanks a lot, I'm already use it for evaluation purposes. Looking forward to see it on rubygems anytime soon.
