### ISSUE TITLE
missing return code checking & response

### ISSUE THREAD

**Issue by nichenke** [TheJumpCloud/jumpcloud-ruby-gem#4]
When using the following script:

```ruby
#!/usr/local/bin/ruby

require 'rubygems'
require 'base64'
require 'jumpcloud'

tags = %w(group2,group1)

JumpCloud.set_system_tags(*tags)
```

It fails, but there is no logging of what,why or even a response code returned. It would really help automation if these two items existed.

**Comment by jamesbrown7** [comment]
Understood, Nic, and thanks for the feedback. We've got this captured as a feature request.

**Comment by nichenke** [comment]
Great!
