### ISSUE TITLE
Version 0.4.0 released on rubygems, this repo only has up to 0.3.0

### ISSUE THREAD

**Issue by tkling** [TheJumpCloud/jumpcloud-ruby-gem#5]
I was about to start writing some code to fix the [open issue](https://github.com/TheJumpCloud/jumpcloud-ruby-gem/issues/3) on this repo, then noticed that the reporter copy and pasted some paths that indicated version 0.4.0 was installed. I double checked on RubyGems - [0.4.0 is released there](https://rubygems.org/gems/jumpcloud) and has ~3300 downloads.

Version 0.4.0 should get pushed here please :)

**Comment by jamesbrown7** [comment]
Sorry, for some reason the updated gemspec did not get pushed. This repo contains the 0.4.0 code otherwise.

**Comment by tkling** [comment]
Ahh cool, thanks!
